version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: liondb
    ports:
      - "3306:3306"

  backend:
    build: ./board_backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/liondb

  frontend:
    build: ./board_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
